### ISSUE TITLE
maxPacketLength(1500)

### ISSUE THREAD

**Issue by benjamintxn** [yamcs/quickstart#24]
How can I adjust the maxPacketLength?

15:09:43.149 VITA_BT_COMMS [43] TcpTmDataLink [tcp-in-Images] Cannot open or read TM socket localhost: 10018: java.io.IOException: Invalid packet read: packetLength (26182) > maxPacketLength(1500). Retrying in 10 seconds.

**Comment by fqqb** [comment]
add something like this to the link's args (assuming you're using CCSDS-style packets):

```yaml
packetInputStreamClassName: org.yamcs.tctm.CcsdsPacketInputStream
packetInputStreamArgs:
  maxPacketLength: 30000
```
